### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by cepalle** [ArthurMatthys/VR_app#1]
C'est quoi =o ?

**Comment by AlexisVisco** [comment]
Un projet pour une entreprise 🙂
Il doit implémenter from scratch une sorte de vr.

Il trace deux points et quand il bouge les points bougent aussi dans l'espace !

**Comment by cepalle** [comment]
cool !

**Comment by ArthurMatthys** [comment]
Je vais pas mettre un ReadMe quand le projet est pas encore fini si ? Je sais comment il marche mon projet :)

**Comment by cepalle** [comment]
un README c'est pas à faire forcement à la fin et ce n'est pas toi principal destinataire^^
